import assert from "node:assert/strict";
import { mkdtemp, cp, readFile, writeFile, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import test from "node:test";
const root = path.resolve(import.meta.dirname, "..");
const validator = path.join(root, "scripts", "validate_version_integrity.py");
async function fixture() {
  const dir = await mkdtemp(path.join(os.tmpdir(), "fde-version-"));
  for (const item of [
    "package.json", "package-lock.json", "CITATION.cff", "project-facts.json",
    "README.md", "examples", "docs", "site", "schemas", "scripts",
  ]) await cp(path.join(root, item), path.join(dir, item), { recursive: true });
  return dir;
}
function run(dir) { return spawnSync("python3", [validator, "--root", dir], { encoding: "utf8" }); }
async function fixtureVersion(dir) {
  const packageData = JSON.parse(await readFile(path.join(dir, "package.json"), "utf8"));
  return packageData.version;
}
async function replaceRequired(file, from, to) {
  const before = await readFile(file, "utf8");
  assert.ok(before.includes(from), `expected fixture text not found: ${from}`);
  const after = before.replace(from, to);
  assert.notEqual(after, before, `fixture mutation did not change ${file}`);
  await writeFile(file, after);
}
test("version authorities agree", async () => {
  const dir = await fixture();
  const result = run(dir);
  assert.equal(result.status, 0, result.stdout + result.stderr);
});
test("stale citation fails", async () => {
  const dir = await fixture();
  const p = path.join(dir, "CITATION.cff");
  const version = await fixtureVersion(dir);
  await replaceRequired(p, `version: ${version}`, "version: 0.0.0");
  assert.notEqual(run(dir).status, 0);
});
test("stale generated facts fail", async () => {
  const dir = await fixture();
  const p = path.join(dir, "project-facts.json");
  const obj = JSON.parse(await readFile(p, "utf8")); obj.applicationVersion = "0.2.12";
  await writeFile(p, JSON.stringify(obj, null, 2) + "\n");
  assert.notEqual(run(dir).status, 0);
});
test("stale package lock fails", async () => {
  const dir = await fixture();
  const p = path.join(dir, "package-lock.json");
  const obj = JSON.parse(await readFile(p, "utf8")); obj.version = "0.2.12";
  await writeFile(p, JSON.stringify(obj, null, 2) + "\n");
  assert.notEqual(run(dir).status, 0);
});
test("missing current release notes fail", async () => {
  const dir = await fixture();
  const version = await fixtureVersion(dir);
  await rm(path.join(dir, "docs", "releases", `v${version}.md`));
  assert.notEqual(run(dir).status, 0);
});
test("stale runtime version module fails", async () => {
  const dir = await fixture();
  await writeFile(path.join(dir, "site", "src", "version.js"), "export const APPLICATION_VERSION = '0.2.12';\n");
  assert.notEqual(run(dir).status, 0);
});
test("hard-coded readable-export application version fails", async () => {
  const dir = await fixture();
  const p = path.join(dir, "site", "src", "decision-ui.js");
  await writeFile(p, (await readFile(p, "utf8")).replace("Generated by Frontier Decision Engine v${APPLICATION_VERSION}.", "Generated by Frontier Decision Engine v0.2.12."));
  assert.notEqual(run(dir).status, 0);
});
test("stale README screenshot path fails", async () => {
  const dir = await fixture();
  const p = path.join(dir, "README.md");
  const version = await fixtureVersion(dir);
  await replaceRequired(
    p,
    `docs/screenshots/v${version}/`,
    "docs/screenshots/v0.0.0/",
  );
  assert.notEqual(run(dir).status, 0);
});
test("hard-coded screenshot capture version fails", async () => {
  const dir = await fixture();
  const p = path.join(dir, "scripts", "capture_screenshots.py");
  await writeFile(
    p,
    (await readFile(p, "utf8")).replace(
      'VERSION = json.loads((ROOT / "package.json").read_text(encoding="utf-8"))["version"]',
      'VERSION = "0.2.12"',
    ),
  );
  assert.notEqual(run(dir).status, 0);
});
