#!/usr/bin/env python3
from __future__ import annotations
import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

def fail(message: str, errors: list[str]) -> None:
    errors.append(message)

def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=None)
    args = parser.parse_args()
    root = Path(args.root).resolve() if args.root else Path(__file__).resolve().parents[1]
    errors: list[str] = []
    def load_json(path: str):
        try:
            return json.loads((root / path).read_text(encoding="utf-8"))
        except Exception as exc:
            fail(f"invalid JSON {path}: {exc}", errors)
            return {}
    def load_text(path: str) -> str:
        try:
            return (root / path).read_text(encoding="utf-8")
        except Exception as exc:
            fail(f"invalid text {path}: {exc}", errors)
            return ""

    package = load_json("package.json")
    lock = load_json("package-lock.json")
    facts = load_json("project-facts.json")
    interfaces = load_json("INTERFACES.json")
    decision = load_json("examples/synthetic-source-qualification/decision.fde.json")
    semantic_schema = load_json("schemas/decision-0.3.0.schema.json")
    deployed_semantic_schema = load_json("site/schemas/decision-0.3.0.schema.json")
    legacy_mission_context_schema = load_json("schemas/mission-graph-decision-context-0.2.0.schema.json")
    deployed_legacy_mission_context_schema = load_json("site/schemas/mission-graph-decision-context-0.2.0.schema.json")
    mission_context_schema = load_json("schemas/mission-graph-decision-context-0.3.0.schema.json")
    deployed_mission_context_schema = load_json("site/schemas/mission-graph-decision-context-0.3.0.schema.json")
    version = str(package.get("version", ""))
    if not re.fullmatch(r"\d+\.\d+\.\d+", version):
        fail(f"invalid package version: {version!r}", errors)
    if str(lock.get("version", "")) != version:
        fail("package-lock top-level version does not match package.json", errors)
    if str(lock.get("packages", {}).get("", {}).get("version", "")) != version:
        fail("package-lock root package version does not match package.json", errors)
    citation = load_text("CITATION.cff")
    if not re.search(rf"(?m)^version:\s*{re.escape(version)}\s*$", citation):
        fail("CITATION.cff version does not match package.json", errors)
    if str(facts.get("applicationVersion", "")) != version:
        fail("project-facts applicationVersion does not match package.json", errors)
    release_note = root / "docs" / "RELEASE_NOTES.md"
    if not release_note.is_file():
        fail("current release notes are missing: docs/RELEASE_NOTES.md", errors)
    else:
        notes = load_text("docs/RELEASE_NOTES.md")
        if not re.search(rf"(?m)^#\s+v{re.escape(version)}\s*$", notes):
            fail("RELEASE_NOTES.md does not identify the current application version", errors)

    runtime_module = load_text("site/src/version.js")
    expected_module = f"export const APPLICATION_VERSION = '{version}';\n"
    if runtime_module != expected_module:
        fail("site/src/version.js does not match package.json", errors)
    decision_ui = load_text("site/src/decision-ui.js")
    if "import { APPLICATION_VERSION } from './version.js';" not in decision_ui:
        fail("readable export does not import the application-version authority", errors)
    if "Generated by Frontier Decision Engine v${APPLICATION_VERSION}." not in decision_ui:
        fail("readable export does not render the application-version authority", errors)
    if re.search(r"Generated by Frontier Decision Engine v\d+\.\d+\.\d+", decision_ui):
        fail("readable export contains a hard-coded application version", errors)
    readme = load_text("README.md")
    expected_screenshot = "docs/screenshots/reference/desktop-decision-frame.png"
    if expected_screenshot not in readme:
        fail("README does not use the stable reference screenshot", errors)
    capture = load_text("scripts/capture_screenshots.py")
    if 'OUTPUT = ROOT / "docs" / "screenshots" / "reference"' not in capture:
        fail("screenshot capture does not use the stable reference directory", errors)
    if 'f"v{VERSION}"' in capture:
        fail("screenshot capture still creates version-per-release directories", errors)
    screenshot = root / expected_screenshot
    if not screenshot.is_file():
        fail(f"current README screenshot is missing: {expected_screenshot}", errors)

    schema = str(facts.get("schemaVersions", {}).get("decision", ""))
    if schema != str(decision.get("schema_version", "")):
        fail("decision example schema does not match project-facts", errors)
    if schema != "0.2.10":
        fail(f"unexpected decision schema change: {schema}", errors)
    semantic_schema_version = semantic_schema.get("properties", {}).get("schema_version", {}).get("const")
    if semantic_schema_version != "0.3.0":
        fail("parallel semantic decision schema 0.3.0 is missing or invalid", errors)
    if facts.get("schemaVersions", {}).get("semanticDecision") != semantic_schema_version:
        fail("project-facts semantic decision schema does not match schema 0.3.0", errors)
    if semantic_schema != deployed_semantic_schema:
        fail("source and deployed semantic decision schemas differ", errors)

    if legacy_mission_context_schema.get("$id") != "urn:bn7:decision-context:0.2.0":
        fail("legacy Mission Graph Decision Context Packet 0.2.0 consumer schema identity is invalid", errors)
    legacy_properties = legacy_mission_context_schema.get("properties", {})
    if legacy_properties.get("schema_version", {}).get("const") != "0.2.0":
        fail("legacy Mission Graph Decision Context Packet version contract changed unexpectedly", errors)
    if legacy_properties.get("compatibility", {}).get("const") != "FDE_PREPARATION_ONLY":
        fail("legacy Mission Graph FDE preparation boundary changed unexpectedly", errors)
    if legacy_properties.get("classification", {}).get("enum") != ["PRIVATE", "PROTECTED"]:
        fail("legacy Mission Graph context classification boundary changed unexpectedly", errors)
    if legacy_mission_context_schema != deployed_legacy_mission_context_schema:
        fail("source and deployed legacy Mission Graph Decision Context schemas differ", errors)

    if mission_context_schema.get("$id") != "urn:bn7:decision-context:0.3.0":
        fail("Mission Graph Decision Context Packet 0.3.0 consumer schema identity is invalid", errors)
    properties = mission_context_schema.get("properties", {})
    if properties.get("schema_version", {}).get("const") != "0.3.0":
        fail("Mission Graph Decision Context Packet 0.3.0 version contract is invalid", errors)
    if properties.get("compatibility", {}).get("const") != "FDE_PREPARATION_ONLY":
        fail("Mission Graph FDE preparation boundary changed unexpectedly", errors)
    if properties.get("classification", {}).get("enum") != ["PRIVATE", "PROTECTED"]:
        fail("Mission Graph context classification boundary changed unexpectedly", errors)
    handling = properties.get("handling", {}).get("properties", {})
    if handling.get("government_classification", {}).get("const") is not False:
        fail("Mission Graph internal handling label could be confused with government classification", errors)
    if handling.get("release_eligible", {}).get("const") is not False:
        fail("Mission Graph context release boundary changed unexpectedly", errors)
    integrity = properties.get("integrity", {}).get("properties", {})
    if integrity.get("payload_scope", {}).get("const") != "decision-relevant packet content excluding integrity, origin, freshness, and provenance":
        fail("Mission Graph payload digest scope changed unexpectedly", errors)
    if integrity.get("envelope_scope", {}).get("const") != "packet excluding the envelope digest field and origin.attestation_ref":
        fail("Mission Graph envelope digest scope changed unexpectedly", errors)
    origin = properties.get("origin", {}).get("properties", {})
    if origin.get("authentication_state", {}).get("enum") != ["UNAUTHENTICATED", "AUTHENTICATED"]:
        fail("Mission Graph origin-authentication contract changed unexpectedly", errors)
    if mission_context_schema != deployed_mission_context_schema:
        fail("source and deployed Mission Graph Decision Context 0.3.0 schemas differ", errors)

    if interfaces.get("format") != "bn7.interfaces/0.1":
        fail("INTERFACES.json format is invalid", errors)
    if interfaces.get("system") != "frontier-decision-engine":
        fail("INTERFACES.json system identity is invalid", errors)
    if "application_version" in interfaces:
        fail("INTERFACES.json must remain independent from application version", errors)
    accepts = interfaces.get("accepts", [])
    if not isinstance(accepts, list) or len(accepts) != 1 or not isinstance(accepts[0], dict):
        fail("INTERFACES.json must declare exactly one bounded accepted DCP interface", errors)
    else:
        accepted = accepts[0]
        expected_path = "schemas/mission-graph-decision-context-0.3.0.schema.json"
        if accepted.get("contract_id") != "urn:bn7:decision-context:0.3.0":
            fail("accepted DCP contract identity is invalid", errors)
        if accepted.get("contract_version") != "0.3.0":
            fail("accepted DCP contract version is invalid", errors)
        if accepted.get("schema_path") != expected_path:
            fail("accepted DCP schema path is invalid", errors)
        if accepted.get("profile") != "FDE_PREPARATION_ONLY":
            fail("accepted DCP semantic profile is invalid", errors)
        if accepted.get("authority") != "CONSUMER_VALIDATES_PRODUCER_OWNED_PORTABLE_CONTRACT":
            fail("accepted DCP authority declaration is invalid", errors)
        actual_digest = hashlib.sha256((root / expected_path).read_bytes()).hexdigest()
        if accepted.get("sha256") != actual_digest:
            fail("accepted DCP raw schema SHA-256 does not match source bytes", errors)

    governed_context = load_text("site/src/lib/governed-context.js")
    if "const ENVELOPE_SCOPE = 'packet excluding the envelope digest field and origin.attestation_ref';" not in governed_context:
        fail("runtime governed-context envelope scope is not aligned with the 0.3.0 consumer schema", errors)
    if "Public FDE cannot accept a self-asserted authenticated origin" not in governed_context:
        fail("runtime governed-context origin boundary is missing", errors)

    if errors:
        print("VERSION INTEGRITY FAILED")
        for error in errors:
            print(f"- {error}")
        return 1
    print(f"VERSION INTEGRITY PASS — application {version}; legacy decision schema {schema}; semantic decision schema 0.3.0; Mission Graph context 0.3.0 (legacy 0.2.0 inspection-only)")
    return 0

if __name__ == "__main__":
    sys.exit(main())
